/**
 * @fileoverview gRPC-Web generated client stub for status
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: status.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.status = require('./status_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.status.StatusStreamerClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.status.StatusStreamerPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.status.StatusRequest,
 *   !proto.status.StatusUpdate>}
 */
const methodDescriptor_StatusStreamer_StreamStatus = new grpc.web.MethodDescriptor(
  '/status.StatusStreamer/StreamStatus',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.status.StatusRequest,
  proto.status.StatusUpdate,
  /**
   * @param {!proto.status.StatusRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.status.StatusUpdate.deserializeBinary
);


/**
 * @param {!proto.status.StatusRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.status.StatusUpdate>}
 *     The XHR Node Readable Stream
 */
proto.status.StatusStreamerClient.prototype.streamStatus =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/status.StatusStreamer/StreamStatus',
      request,
      metadata || {},
      methodDescriptor_StatusStreamer_StreamStatus);
};


/**
 * @param {!proto.status.StatusRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.status.StatusUpdate>}
 *     The XHR Node Readable Stream
 */
proto.status.StatusStreamerPromiseClient.prototype.streamStatus =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/status.StatusStreamer/StreamStatus',
      request,
      metadata || {},
      methodDescriptor_StatusStreamer_StreamStatus);
};


module.exports = proto.status;

