# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: status.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cstatus.proto\x12\x06status\"\x1b\n\rStatusRequest\x12\n\n\x02id\x18\x01 \x01(\t\"/\n\x0cStatusUpdate\x12\r\n\x05state\x18\x01 \x01(\t\x12\x10\n\x08progress\x18\x02 \x01(\x05\x32O\n\x0eStatusStreamer\x12=\n\x0cStreamStatus\x12\x15.status.StatusRequest\x1a\x14.status.StatusUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUSREQUEST']._serialized_start=24
  _globals['_STATUSREQUEST']._serialized_end=51
  _globals['_STATUSUPDATE']._serialized_start=53
  _globals['_STATUSUPDATE']._serialized_end=100
  _globals['_STATUSSTREAMER']._serialized_start=102
  _globals['_STATUSSTREAMER']._serialized_end=181
# @@protoc_insertion_point(module_scope)
